"use client";

import React from "react";
import { SimulationStats, SimulationParams } from "@/lib/quant/engine";
import {
    ShieldCheck,
    AlertOctagon,
    CheckCircle2,
    TrendingUp,
    Activity,
    Calendar,
    ArrowRight,
    Zap,
    Download,
    Info,
    Lock,
    Crown
} from "lucide-react";
import { cn } from "@/lib/utils";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/contexts/AuthContext";
import Link from "next/link";

interface RiskAuditReportProps {
    stats: SimulationStats | null;
    params: SimulationParams;
}

export function RiskAuditReport({ stats, params }: RiskAuditReportProps) {
    const { isPro } = useAuth();

    if (!stats) return null;

    const { distribution, metrics, violations } = stats;
    const isCompliant = !violations.consistencyBreach && !violations.minDaysBreach;

    // Logic for narrative generation
    const getRiskStatus = () => {
        if (distribution.ruinProbability > 20) return { label: "HIGH RISK", color: "text-rose-500", bg: "bg-rose-500/10", border: "border-rose-500/20" };
        if (distribution.ruinProbability > 5) return { label: "MODERATE RISK", color: "text-amber-500", bg: "bg-amber-500/10", border: "border-amber-500/20" };
        return { label: "INSTITUTIONAL GRADE", color: "text-emerald-500", bg: "bg-emerald-500/10", border: "border-emerald-500/20" };
    };

    const status = getRiskStatus();

    const handleDownload = () => {
        if (!isPro) return;

        const report = `
QUANTITATIVE RISK AUDIT REPORT
Generated by QuantRiskMetrics Engine
Date: ${new Date().toLocaleString()}
------------------------------------------------
FIRM PROFILE: ${params.rules?.drawdownType || 'Custom'}
COMPLIANCE STATUS: ${isCompliant ? 'PASS' : 'FAIL'}
------------------------------------------------
[PERFORMANCE ANALYTICS]
Success Probability: ${distribution.successProbability.toFixed(2)}%
Ruin Probability:    ${distribution.ruinProbability.toFixed(2)}%
Sharpe Ratio:        ${metrics.sharpeRatio.toFixed(2)}
Ulcer Index:         ${metrics.ulcerIndex.toFixed(2)}
Consistency Score:   ${metrics.consistencyScore.toFixed(1)}/100

[VIOLATIONS DETECTED]
Consistency Breach:  ${violations.consistencyBreach ? 'YES' : 'NO'}
Min Days Breach:     ${violations.minDaysBreach ? 'YES' : 'NO'}

[AUDIT SUMMARY]
${distribution.ruinProbability > 5
                ? `WARNING: High ruin probability detected. Adjust risk management.`
                : "Strategy stability within institutional parameters."}
        `.trim();

        const blob = new Blob([report], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `RiskAudit_${new Date().toISOString().slice(0, 10)}.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    return (
        <section className="mt-12 animate-in-slide-up" style={{ animationDelay: '0.6s' }}>
            <div className="flex items-center justify-between mb-6">
                <div className="flex items-center gap-3">
                    <div className="p-2 rounded-lg bg-blue-500/10 border border-blue-500/20">
                        <ShieldCheck className="w-5 h-5 text-blue-500" />
                    </div>
                    <div>
                        <div className="flex items-center gap-2">
                            <h2 className="text-2xl font-bold text-white font-outfit tracking-tight">Account Health Report</h2>
                            {!isPro && (
                                <Link href="/pricing">
                                    <div className="flex items-center gap-1 px-1.5 py-0.5 rounded bg-amber-500/10 border border-amber-500/20 cursor-pointer hover:bg-amber-500/20 transition-colors active:scale-95">
                                        <Crown className="w-2.5 h-2.5 text-amber-500" />
                                        <span className="text-[8px] font-bold text-amber-500 uppercase tracking-widest">Pro Only</span>
                                    </div>
                                </Link>
                            )}
                        </div>
                        <p className="text-sm text-slate-500 font-serif italic">Deep-layer consistency & compliance analysis</p>
                    </div>
                </div>
                <Button
                    variant="outline"
                    size="sm"
                    onClick={handleDownload}
                    className="gap-2 border-white/5 bg-slate-900/50 hover:bg-slate-800"
                    disabled={!isPro}
                >
                    <Download className="w-4 h-4" />
                    {isPro ? "Export PDF/Text" : "Locked (Pro Only)"}
                </Button>
            </div>

            <div className="relative group">
                {/* LOCKED OVERLAY */}
                {!isPro && (
                    <div className="absolute inset-0 z-20 flex items-center justify-center p-4">
                        <div className="absolute inset-0 bg-slate-950/40 backdrop-blur-[8px] rounded-3xl border border-white/5" />
                        <div className="relative text-center p-8 space-y-6 max-w-sm animate-in-zoom">
                            <div className="mx-auto w-16 h-16 rounded-full bg-slate-900 flex items-center justify-center border border-amber-500/30 shadow-glow-amber">
                                <Lock className="w-8 h-8 text-amber-500" />
                            </div>
                            <div className="space-y-2">
                                <h3 className="text-xl font-bold text-white font-outfit uppercase tracking-tight">Institutional Audit Locked</h3>
                                <p className="text-sm text-slate-400">Upgrade to PRO to access structural stability analysis, Sharpe quality reporting, and firm-compliance scoring.</p>
                            </div>
                            <Link href="/pricing" className="w-full">
                                <Button className="w-full bg-amber-500 hover:bg-amber-400 text-slate-950 font-bold uppercase tracking-widest py-6 shadow-glow-amber border-none text-xs">
                                    <Crown className="w-4 h-4 mr-2" />
                                    Go Pro to Unlock Audit
                                </Button>
                            </Link>
                            <p className="text-[10px] text-slate-500 font-mono">ULTRA-HIGH PRECISION (50K PATHS) INCLUDED</p>
                        </div>
                    </div>
                )}

                <div className={cn(
                    "grid grid-cols-1 lg:grid-cols-3 gap-6 transition-all duration-700",
                    !isPro && "opacity-40 select-none grayscale-[0.5]"
                )}>
                    {/* Status Card */}
                    <Card className={cn("glass relative overflow-hidden transition-all duration-500", status.border)}>
                        <div className={cn("absolute top-0 right-0 w-32 h-32 blur-[60px] -mr-16 -mt-16 rounded-full opacity-20", status.color.replace('text', 'bg'))} />
                        <CardHeader>
                            <CardTitle className="text-xs font-bold uppercase tracking-widest text-slate-500 flex items-center justify-between">
                                Audit Status
                                <div className={cn("px-2 py-0.5 rounded-full text-[10px] border", status.bg, status.color, status.border)}>
                                    {status.label}
                                </div>
                            </CardTitle>
                        </CardHeader>
                        <CardContent className="space-y-6">
                            <div className="flex items-center gap-4">
                                <div className={cn("w-16 h-16 rounded-2xl flex items-center justify-center text-3xl font-black shadow-2xl", status.bg, status.color)}>
                                    {Math.round(distribution.successProbability)}%
                                </div>
                                <div>
                                    <div className="text-lg font-bold text-white leading-tight">Projected Alpha</div>
                                    <div className="text-xs text-slate-500">Survival probability score</div>
                                </div>
                            </div>

                            <div className="pt-4 border-t border-white/5 space-y-4">
                                <AuditRow
                                    label="Risk Control"
                                    value={distribution.ruinProbability < 5 ? "STABLE" : "LEVERAGED"}
                                    icon={TrendingUp}
                                    status={distribution.ruinProbability < 5 ? "success" : "warning"}
                                />
                                <AuditRow
                                    label="Sharpe Quality"
                                    value={metrics.sharpeRatio > 1.5 ? "HIGH" : metrics.sharpeRatio > 0.5 ? "AVERAGE" : "LOW"}
                                    icon={Zap}
                                    status={metrics.sharpeRatio > 1.0 ? "success" : "warning"}
                                />
                                <AuditRow
                                    label="Drawdown Stress"
                                    value={metrics.ulcerIndex < 3 ? "LOW" : metrics.ulcerIndex < 8 ? "MEDIUM" : "SEVERE"}
                                    icon={Activity}
                                    status={metrics.ulcerIndex < 5 ? "success" : "error"}
                                />
                            </div>
                        </CardContent>
                    </Card>

                    {/* Consistency Analysis */}
                    <Card className="glass lg:col-span-2">
                        <CardHeader>
                            <CardTitle className="text-xs font-bold uppercase tracking-widest text-slate-500">Institutional Consistency Analysis</CardTitle>
                        </CardHeader>
                        <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-8">
                            <div className="space-y-6">
                                <div className="p-4 rounded-xl bg-slate-950/50 border border-white/5 space-y-3">
                                    <div className="flex items-center justify-between">
                                        <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">Consistency Score</span>
                                        <span className={cn("text-xs font-mono font-bold", metrics.consistencyScore > 70 ? "text-emerald-500" : "text-amber-500")}>
                                            {metrics.consistencyScore.toFixed(1)}/100
                                        </span>
                                    </div>
                                    <div className="h-1.5 w-full bg-slate-900 rounded-full overflow-hidden">
                                        <div
                                            className={cn("h-full transition-all duration-1000", metrics.consistencyScore > 70 ? "bg-emerald-500 shadow-glow-emerald" : "bg-amber-500 shadow-glow-amber")}
                                            style={{ width: `${metrics.consistencyScore}%` }}
                                        />
                                    </div>
                                    <p className="text-[10px] text-slate-500 leading-relaxed font-serif italic">
                                        Measures profit distribution across simulated trades. High scores indicate stable equity growth without "outlier luck" dependence.
                                    </p>
                                </div>

                                <div className="space-y-4">
                                    <div className="flex items-start gap-3">
                                        <div className={cn("mt-1 p-1 rounded-full", violations.consistencyBreach ? "bg-rose-500/20 text-rose-500" : "bg-emerald-500/20 text-emerald-500")}>
                                            {violations.consistencyBreach ? <AlertOctagon className="w-3 h-3" /> : <CheckCircle2 className="w-3 h-3" />}
                                        </div>
                                        <div>
                                            <div className="text-xs font-bold text-white uppercase tracking-tight">Single Day Cap</div>
                                            <p className="text-[11px] text-slate-500 leading-tight">
                                                {violations.consistencyBreach
                                                    ? "Detected simulations where single-day profits exceeded firm thresholds (Luck Factor High)."
                                                    : "Profits are balanced across trading days. Compliant with strict firm rules."}
                                            </p>
                                        </div>
                                    </div>
                                    <div className="flex items-start gap-3">
                                        <div className={cn("mt-1 p-1 rounded-full", violations.minDaysBreach ? "bg-rose-500/20 text-rose-500" : "bg-emerald-500/20 text-emerald-500")}>
                                            {violations.minDaysBreach ? <AlertOctagon className="w-3 h-3" /> : <CheckCircle2 className="w-3 h-3" />}
                                        </div>
                                        <div>
                                            <div className="text-xs font-bold text-white uppercase tracking-tight">Temporal Adherence</div>
                                            <p className="text-[11px] text-slate-500 leading-tight">
                                                {violations.minDaysBreach
                                                    ? "Simulation paths hit targets too fast, violating minimum trading day requirements."
                                                    : "Strategy duration aligns with institutional time-horizon mandates."}
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div className="bg-slate-950/30 rounded-2xl p-6 border border-white/5 flex flex-col justify-between">
                                <div>
                                    <h4 className="text-xs font-bold text-white mb-4 flex items-center gap-2">
                                        <Info className="w-3.5 h-3.5 text-blue-500" />
                                        Quantitative Summary
                                    </h4>
                                    <div className="space-y-4 text-[11px] text-slate-400 leading-relaxed font-serif">
                                        {distribution.ruinProbability < 5 && isCompliant ? (
                                            <p>
                                                Analysis indicates a <span className="text-emerald-500 font-bold">Stable Alpha Profile</span>.
                                                The strategy exhibits institutional-grade risk control with a Sharpe Ratio of {metrics.sharpeRatio.toFixed(2)}.
                                                Wait-times for funding likely minimal.
                                            </p>
                                        ) : (
                                            <p>
                                                The model flags <span className="text-rose-500 font-bold">Structural Instability</span>.
                                                High Ulcer Index ({metrics.ulcerIndex.toFixed(1)}) suggesting significant psychological pressure.
                                                Recommend reducing risk per trade by {((Math.abs(params.riskPerTrade - metrics.propSafeKelly)) * 100).toFixed(1)}%.
                                            </p>
                                        )}
                                        <p>
                                            Average consistency ratio detected at <span className="text-white">{(100 - metrics.consistencyScore).toFixed(1)}%</span>.
                                            This suggests a reliance on individual high-RR trades rather than compounding.
                                        </p>
                                    </div>
                                </div>

                                <div className="pt-6">
                                    <Button
                                        className="w-full bg-blue-600 hover:bg-blue-500 text-white font-bold text-xs uppercase tracking-widest py-6 group"
                                        onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
                                    >
                                        Adjust Strategy Parameters
                                        <ArrowRight className="w-4 h-4 ml-2 transition-transform group-hover:translate-x-1" />
                                    </Button>
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                </div>
            </div>
        </section>
    );
}

function AuditRow({ label, value, icon: Icon, status }: { label: string, value: string, icon: React.ElementType, status: 'success' | 'warning' | 'error' }) {
    const colorClass = status === 'success' ? 'text-emerald-500' : status === 'warning' ? 'text-amber-500' : 'text-rose-500';
    return (
        <div className="flex items-center justify-between group/row cursor-default">
            <div className="flex items-center gap-2.5">
                <Icon className="w-3.5 h-3.5 text-slate-500 group-hover/row:text-blue-400 transition-colors" />
                <span className="text-[11px] font-bold text-slate-400 uppercase tracking-widest group-hover/row:text-slate-300 transition-colors">{label}</span>
            </div>
            <span className={cn("text-[11px] font-mono font-bold transition-all group-hover/row:scale-110", colorClass)}>{value}</span>
        </div>
    );
}
